language: python
python:
  - "3.5"
  - "3.6"

compiler: gcc
dist: trusty

notifications:
  email: false

git:
  submodules: false
  
before_install:
  # C++14 stuff
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # python stuff
  #- sudo apt-get install python3-pip
  #- sudo apt-get install python3-numpy
  #- sudo apt-get install python3-scipy
  
install:
  # new gcc
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  # python packages
  #- python3 -m pip install --only-binary=numpy numpy
  
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy>=1.12 scipy
  - source activate test-environment
  #- python setup.py install
  
  - python -m pip install -r requirements.txt
  - CC=gcc-5.4 CXX=g++-5 python setup.py install
  #- sudo python3 -m pip install -r requirements.txt
  #- sudo CC=gcc-6 CXX=g++-6 python3 setup.py install

script: 
  - python setup.py test